//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen .\CAP-v1.2.xsd
namespace CAP
{
    
    
    /// <summary>
    /// <para>CAP Alert Message (version 1.2)</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("CAP Alert Message (version 1.2)")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("alert", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("alert", Namespace="urn:oasis:names:tc:emergency:cap:1.2")]
    public partial class Alert
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("identifier")]
        public string Identifier { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("sender")]
        public string Sender { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: \d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d[-,+]\d\d:\d\d.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d\\d\\d\\d-\\d\\d-\\d\\dT\\d\\d:\\d\\d:\\d\\d[-,+]\\d\\d:\\d\\d")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("sent", DataType="dateTime")]
        public System.DateTime Sent { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("status")]
        public AlertStatus Status { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("msgType")]
        public AlertMsgType MsgType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("source")]
        public string Source { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("scope")]
        public AlertScope Scope { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("restriction")]
        public string Restriction { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("addresses")]
        public string Addresses { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _code;
        
        [System.Xml.Serialization.XmlElementAttribute("code")]
        public System.Collections.ObjectModel.Collection<string> Code
        {
            get
            {
                return _code;
            }
            private set
            {
                _code = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Code collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodeSpecified
        {
            get
            {
                return (this.Code.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Alert" /> class.</para>
        /// </summary>
        public Alert()
        {
            this._code = new System.Collections.ObjectModel.Collection<string>();
            this._info = new System.Collections.ObjectModel.Collection<AlertInfo>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.XmlElement>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("note")]
        public string Note { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("references")]
        public string References { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("incidents")]
        public string Incidents { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AlertInfo> _info;
        
        [System.Xml.Serialization.XmlElementAttribute("info")]
        public System.Collections.ObjectModel.Collection<AlertInfo> Info
        {
            get
            {
                return _info;
            }
            private set
            {
                _info = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Info collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfoSpecified
        {
            get
            {
                return (this.Info.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.XmlElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertStatus", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    public enum AlertStatus
    {
        
        Actual,
        
        Exercise,
        
        System,
        
        Test,
        
        Draft,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertMsgType", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    public enum AlertMsgType
    {
        
        Alert,
        
        Update,
        
        Cancel,
        
        Ack,
        
        Error,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertScope", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    public enum AlertScope
    {
        
        Public,
        
        Restricted,
        
        Private,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertInfo", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlertInfo
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _language = "en-US";
        
        [System.ComponentModel.DefaultValueAttribute("en-US")]
        [System.Xml.Serialization.XmlElementAttribute("language")]
        public string Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AlertInfoCategory> _category;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("category")]
        public System.Collections.ObjectModel.Collection<AlertInfoCategory> Category
        {
            get
            {
                return _category;
            }
            private set
            {
                _category = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AlertInfo" /> class.</para>
        /// </summary>
        public AlertInfo()
        {
            this._category = new System.Collections.ObjectModel.Collection<AlertInfoCategory>();
            this._responseType = new System.Collections.ObjectModel.Collection<AlertInfoResponseType>();
            this._eventCode = new System.Collections.ObjectModel.Collection<AlertInfoEventCode>();
            this._parameter = new System.Collections.ObjectModel.Collection<AlertInfoParameter>();
            this._resource = new System.Collections.ObjectModel.Collection<AlertInfoResource>();
            this._area = new System.Collections.ObjectModel.Collection<AlertInfoArea>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("event")]
        public string Event { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AlertInfoResponseType> _responseType;
        
        [System.Xml.Serialization.XmlElementAttribute("responseType")]
        public System.Collections.ObjectModel.Collection<AlertInfoResponseType> ResponseType
        {
            get
            {
                return _responseType;
            }
            private set
            {
                _responseType = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ResponseType collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseTypeSpecified
        {
            get
            {
                return (this.ResponseType.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("urgency")]
        public AlertInfoUrgency Urgency { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("severity")]
        public AlertInfoSeverity Severity { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("certainty")]
        public AlertInfoCertainty Certainty { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("audience")]
        public string Audience { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AlertInfoEventCode> _eventCode;
        
        [System.Xml.Serialization.XmlElementAttribute("eventCode")]
        public System.Collections.ObjectModel.Collection<AlertInfoEventCode> EventCode
        {
            get
            {
                return _eventCode;
            }
            private set
            {
                _eventCode = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the EventCode collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventCodeSpecified
        {
            get
            {
                return (this.EventCode.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: \d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d[-,+]\d\d:\d\d.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d\\d\\d\\d-\\d\\d-\\d\\dT\\d\\d:\\d\\d:\\d\\d[-,+]\\d\\d:\\d\\d")]
        [System.Xml.Serialization.XmlElementAttribute("effective", DataType="dateTime")]
        public System.DateTime Effective { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Effective property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EffectiveSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: \d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d[-,+]\d\d:\d\d.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d\\d\\d\\d-\\d\\d-\\d\\dT\\d\\d:\\d\\d:\\d\\d[-,+]\\d\\d:\\d\\d")]
        [System.Xml.Serialization.XmlElementAttribute("onset", DataType="dateTime")]
        public System.DateTime Onset { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Onset property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OnsetSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: \d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d[-,+]\d\d:\d\d.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d\\d\\d\\d-\\d\\d-\\d\\dT\\d\\d:\\d\\d:\\d\\d[-,+]\\d\\d:\\d\\d")]
        [System.Xml.Serialization.XmlElementAttribute("expires", DataType="dateTime")]
        public System.DateTime Expires { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Expires property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("senderName")]
        public string SenderName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("headline")]
        public string Headline { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("instruction")]
        public string Instruction { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("web")]
        public string Web { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("contact")]
        public string Contact { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AlertInfoParameter> _parameter;
        
        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public System.Collections.ObjectModel.Collection<AlertInfoParameter> Parameter
        {
            get
            {
                return _parameter;
            }
            private set
            {
                _parameter = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Parameter collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParameterSpecified
        {
            get
            {
                return (this.Parameter.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AlertInfoResource> _resource;
        
        [System.Xml.Serialization.XmlElementAttribute("resource")]
        public System.Collections.ObjectModel.Collection<AlertInfoResource> Resource
        {
            get
            {
                return _resource;
            }
            private set
            {
                _resource = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Resource collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResourceSpecified
        {
            get
            {
                return (this.Resource.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AlertInfoArea> _area;
        
        [System.Xml.Serialization.XmlElementAttribute("area")]
        public System.Collections.ObjectModel.Collection<AlertInfoArea> Area
        {
            get
            {
                return _area;
            }
            private set
            {
                _area = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Area collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AreaSpecified
        {
            get
            {
                return (this.Area.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertInfoCategory", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    public enum AlertInfoCategory
    {
        
        Geo,
        
        Met,
        
        Safety,
        
        Security,
        
        Rescue,
        
        Fire,
        
        Health,
        
        Env,
        
        Transport,
        
        Infra,
        
        [System.Xml.Serialization.XmlEnumAttribute("CBRNE")]
        Cbrne,
        
        Other,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertInfoResponseType", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    public enum AlertInfoResponseType
    {
        
        Shelter,
        
        Evacuate,
        
        Prepare,
        
        Execute,
        
        Avoid,
        
        Monitor,
        
        Assess,
        
        AllClear,
        
        None,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertInfoUrgency", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    public enum AlertInfoUrgency
    {
        
        Immediate,
        
        Expected,
        
        Future,
        
        Past,
        
        Unknown,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertInfoSeverity", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    public enum AlertInfoSeverity
    {
        
        Extreme,
        
        Severe,
        
        Moderate,
        
        Minor,
        
        Unknown,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertInfoCertainty", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    public enum AlertInfoCertainty
    {
        
        Observed,
        
        Likely,
        
        Possible,
        
        Unlikely,
        
        Unknown,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertInfoEventCode", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlertInfoEventCode
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("valueName")]
        public string ValueName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertInfoParameter", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlertInfoParameter
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("valueName")]
        public string ValueName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertInfoResource", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlertInfoResource
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("resourceDesc")]
        public string ResourceDesc { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("mimeType")]
        public string MimeType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("size")]
        public string Size { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("uri")]
        public string Uri { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("derefUri")]
        public string DerefUri { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("digest")]
        public string Digest { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertInfoArea", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlertInfoArea
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("areaDesc")]
        public string AreaDesc { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _polygon;
        
        [System.Xml.Serialization.XmlElementAttribute("polygon")]
        public System.Collections.ObjectModel.Collection<string> Polygon
        {
            get
            {
                return _polygon;
            }
            private set
            {
                _polygon = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Polygon collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PolygonSpecified
        {
            get
            {
                return (this.Polygon.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AlertInfoArea" /> class.</para>
        /// </summary>
        public AlertInfoArea()
        {
            this._polygon = new System.Collections.ObjectModel.Collection<string>();
            this._circle = new System.Collections.ObjectModel.Collection<string>();
            this._geocode = new System.Collections.ObjectModel.Collection<AlertInfoAreaGeocode>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _circle;
        
        [System.Xml.Serialization.XmlElementAttribute("circle")]
        public System.Collections.ObjectModel.Collection<string> Circle
        {
            get
            {
                return _circle;
            }
            private set
            {
                _circle = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Circle collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CircleSpecified
        {
            get
            {
                return (this.Circle.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AlertInfoAreaGeocode> _geocode;
        
        [System.Xml.Serialization.XmlElementAttribute("geocode")]
        public System.Collections.ObjectModel.Collection<AlertInfoAreaGeocode> Geocode
        {
            get
            {
                return _geocode;
            }
            private set
            {
                _geocode = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Geocode collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GeocodeSpecified
        {
            get
            {
                return (this.Geocode.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("altitude")]
        public decimal Altitude { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Altitude property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AltitudeSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ceiling")]
        public decimal Ceiling { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Ceiling property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CeilingSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlertInfoAreaGeocode", Namespace="urn:oasis:names:tc:emergency:cap:1.2", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlertInfoAreaGeocode
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("valueName")]
        public string ValueName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string Value { get; set; }
    }
}
